/**
 * GENESIS-IRON-HALO v1.2 — Schema Generator Service
 *
 * "Dynamic Per-Mission Schemas — generated UNIQUELY per mission."
 * "External AIs cannot predict what they'll be asked."
 * "Schema is dead after one use — no replay attacks."
 *
 * Generated by GTC + DARPA + Brighton Protocol intelligence
 * (in v1.2: deterministic generation from operator data).
 *
 * Each schema contains 3-7 unique questions parameterised with
 * mission-specific values. KRYPTONITE operators get extra questions.
 */

import { randomUUID } from "crypto";
import type {
  MissionSchema,
  MissionSchemaQuestion,
  FindingCategory,
  OperatorClass,
  ContaminationLevel,
} from "../../types";

const SCHEMA_EXPIRY_MS = parseInt(process.env.ADVISORY_ZONE_EXPIRY_MS || "60000", 10);

interface SchemaContext {
  missionDurationMs: number;
  pnlUsd?: number;
  gasSpentUsd?: number;
  narrativeLength: number;
  anomalyCount: number;
  chain?: string;
  mempoolCongestion?: string;
  exchangeCount: number;
}

/** Question template pool — parameterised with mission-specific values */
const QUESTION_POOL: Array<{
  category: FindingCategory;
  template: (ctx: SchemaContext) => string;
  responseType: MissionSchemaQuestion["expectedResponseType"];
  bounds?: { min: number; max: number };
  condition?: (ctx: SchemaContext, opClass?: OperatorClass) => boolean;
}> = [
  {
    category: "TIMING_ANOMALY",
    template: (ctx) =>
      `Subject was deployed for ${(ctx.missionDurationMs / 1000).toFixed(0)}s. ` +
      `Given the mission profile and ${ctx.chain || "unknown"} chain, was this duration consistent with successful execution?`,
    responseType: "verdict",
  },
  {
    category: "PNL_ANOMALY",
    template: (ctx) =>
      `Reported PnL is $${(ctx.pnlUsd || 0).toFixed(2)} with gas spend $${(ctx.gasSpentUsd || 0).toFixed(2)}. ` +
      `Given ${ctx.mempoolCongestion || "unknown"} congestion conditions, is this P&L plausible?`,
    responseType: "confidence",
    bounds: { min: 0, max: 1 },
  },
  {
    category: "NARRATIVE_ANOMALY",
    template: (ctx) =>
      `The subject reported ${ctx.narrativeLength} characters of narrative over ` +
      `${(ctx.missionDurationMs / 3600000).toFixed(1)} hours. Assess narrative completeness.`,
    responseType: "verdict",
  },
  {
    category: "GAS_ANOMALY",
    template: (ctx) =>
      `Gas expenditure was $${(ctx.gasSpentUsd || 0).toFixed(2)} on ${ctx.chain || "unknown"} chain. ` +
      `Is this consistent with the reported mission profile?`,
    responseType: "boolean",
  },
  {
    category: "BEHAVIOUR_DRIFT",
    template: (ctx) =>
      `Subject interacted with ${ctx.exchangeCount} exchange(s). ` +
      `Assess whether exchange selection shows operational drift or predictable patterns.`,
    responseType: "narrative",
  },
  {
    category: "CLONE_INDICATOR",
    template: (ctx) =>
      `${ctx.anomalyCount} anomalies were reported during the mission. ` +
      `Assess the probability that this report is a clone or replay.`,
    responseType: "confidence",
    bounds: { min: 0, max: 1 },
  },
  {
    category: "DATA_INCONSISTENCY",
    template: (ctx) =>
      `Cross-reference the reported PnL ($${(ctx.pnlUsd || 0).toFixed(2)}) with gas costs ` +
      `($${(ctx.gasSpentUsd || 0).toFixed(2)}) and mission duration (${(ctx.missionDurationMs / 1000).toFixed(0)}s). ` +
      `Are these internally consistent?`,
    responseType: "verdict",
  },
  {
    category: "MISSION_DEVIATION",
    template: () =>
      `Based on the narrative and conditions, did the subject deviate from expected mission parameters? ` +
      `What is the estimated deviation percentage?`,
    responseType: "narrative",
  },
  // KRYPTONITE-only questions
  {
    category: "TIMING_ANOMALY",
    template: (ctx) =>
      `DEEP ANALYSIS: Subject was embedded for ${(ctx.missionDurationMs / 3600000).toFixed(1)} hours. ` +
      `Are there unexplained time gaps? Could the operator have been captured and returned with planted data?`,
    responseType: "narrative",
    condition: (_, opClass) => opClass === "PHANTOM_STACK",
  },
  {
    category: "DATA_INCONSISTENCY",
    template: () =>
      `FABRICATION CHECK: Does the narrative contain specific details that could be verified ` +
      `independently, or does it read as plausible but unverifiable? Assess fabrication probability.`,
    responseType: "confidence",
    bounds: { min: 0, max: 1 },
    condition: (_, opClass) => opClass === "PHANTOM_STACK",
  },
  {
    category: "CLONE_INDICATOR",
    template: () =>
      `PLANTED INTEL CHECK: Could the intelligence in this report have been specifically crafted ` +
      `to influence our decision-making? Assess manipulation probability.`,
    responseType: "confidence",
    bounds: { min: 0, max: 1 },
    condition: (_, opClass) => opClass === "PHANTOM_STACK",
  },
];

export class SchemaGeneratorService {
  private totalGenerated = 0;

  /**
   * Generate a unique mission schema for this specific operator.
   * Dead after one use. No replay attacks.
   */
  generate(
    operatorClass: OperatorClass | undefined,
    missionType: string,
    contaminationLevel: ContaminationLevel | undefined,
    context: SchemaContext,
  ): MissionSchema {
    const now = new Date();
    const isKryptonite = contaminationLevel === "KRYPTONITE";

    // Filter questions by eligibility (class conditions)
    const eligible = QUESTION_POOL.filter(q => {
      if (q.condition) return q.condition(context, operatorClass);
      return true; // No condition = always eligible
    });

    // Select 3-7 questions (more for KRYPTONITE)
    const baseCount = isKryptonite ? 5 : 3;
    const maxCount = isKryptonite ? 7 : 5;
    const count = Math.min(maxCount, Math.max(baseCount, eligible.length));

    // Shuffle and take — ensures unpredictability
    const shuffled = this.shuffle([...eligible]);
    const selected = shuffled.slice(0, count);

    const questions: MissionSchemaQuestion[] = selected.map(q => ({
      questionId: randomUUID(),
      category: q.category,
      prompt: q.template(context),
      expectedResponseType: q.responseType,
      bounds: q.bounds,
    }));

    this.totalGenerated++;

    return {
      schemaId: randomUUID(),
      questions,
      createdAt: now.toISOString(),
      expiresAt: new Date(now.getTime() + SCHEMA_EXPIRY_MS).toISOString(),
      used: false,
    };
  }

  /**
   * Mark a schema as used — dead after one use.
   */
  markUsed(schema: MissionSchema): void {
    schema.used = true;
    schema.questions = []; // Clear questions — one-time use
  }

  getStats(): { totalGenerated: number } {
    return { totalGenerated: this.totalGenerated };
  }

  /** Fisher-Yates shuffle */
  private shuffle<T>(arr: T[]): T[] {
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr;
  }
}
